; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = airm2m_core_esp32c3

[env]
platform = espressif32
board = airm2m_core_esp32c3
framework = arduino
upload_speed = 115200
monitor_speed = 115200

[env:airm2m_core_esp32c3]
build_src_filter =
    +<main.cpp>
    -<open_drain_test.cpp>

[env:open_drain_test]
build_src_filter =
    -<main.cpp>
    +<open_drain_test.cpp>
build_flags = -DOPEN_DRAIN_TEST_BUILD=1
